[features]
seeds = true
skip-lint = false
[programs.localnet]
anchor_nft_staking = "9EoPTXAXnUC8RjX351GePk9hfZ8Nmjrb9ujYj2JJvxai"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
